name:                algos
version:             0.1.0.0
github:              "githubuser/algos"
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/algos#readme>

dependencies:
- base >= 4.7 && < 5
- array
- data-ordlist
- filepath
- containers

library:
  source-dirs: src

executables:
  algos-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - algos

tests:
  algos-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - algos
    - hspec
    - HUnit
